version: '3'

services:
  server:
    container_name: 'server'
    image: gitlab/gitlab-ce:16.4.3-ce.0
    hostname: "$GITLAB_URL"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url: $GITLAB_URL
      GITLAB_ROOT_PASSWORD: '$GITLAB_HOME_PASSWORD'
    ports:
      - '8080:80'
      - '8443:443'
      - '8022:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'