version: '3'

services:
  server:
    container_name: 'server'
    image: gitlab/gitlab-ce:16.4.3-ce.0
    hostname: "$GITLAB_HOST"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://$GITLAB_HOST'
      GITLAB_ROOT_PASSWORD: '$GITLAB_ROOT_PASSWORD'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'